Repository casimir/frigoligo, pull requests merged in 2024-04, with the labels that each got.

#154 Setup fastlane config and metadata files
  android/.gitignore
  android/Gemfile
  android/Gemfile.lock
  android/fastlane/Fastfile
  android/fastlane/README.md
  android/fastlane/metadata/android/en-GB/full_description.txt
  android/fastlane/metadata/android/en-GB/short_description.txt
  android/fastlane/metadata/android/en-GB/title.txt
  android/fastlane/metadata/android/en-GB/video.txt
  ios/.gitignore
  ios/Gemfile
  ios/Gemfile.lock
  ios/fastlane/Deliverfile
  ios/fastlane/Fastfile
  ios/fastlane/metadata/copyright.txt
  ios/fastlane/metadata/en-GB/apple_tv_privacy_policy.txt
  ios/fastlane/metadata/en-GB/description.txt
  ios/fastlane/metadata/en-GB/keywords.txt
  ios/fastlane/metadata/en-GB/marketing_url.txt
  ios/fastlane/metadata/en-GB/name.txt
  ios/fastlane/metadata/en-GB/privacy_url.txt
  ios/fastlane/metadata/en-GB/promotional_text.txt
  ios/fastlane/metadata/en-GB/release_notes.txt
  ios/fastlane/metadata/en-GB/subtitle.txt
  ios/fastlane/metadata/en-GB/support_url.txt
  ios/fastlane/metadata/primary_category.txt
  ios/fastlane/metadata/primary_first_sub_category.txt
  ios/fastlane/metadata/primary_second_sub_category.txt
  ios/fastlane/metadata/secondary_category.txt
  ios/fastlane/metadata/secondary_first_sub_category.txt
  ios/fastlane/metadata/secondary_second_sub_category.txt
Labels: ops

#155 Translations update from Hosted Weblate
  android/fastlane/metadata/android/en-GB/full_description.txt
  android/fastlane/metadata/android/en-GB/short_description.txt
  android/fastlane/metadata/android/en-GB/title.txt
  android/fastlane/metadata/android/en-GB/video.txt
  android/fastlane/metadata/android/fr-FR/full_description.txt
  android/fastlane/metadata/android/fr-FR/short_description.txt
  ios/fastlane/metadata/en-GB/apple_tv_privacy_policy.txt
  ios/fastlane/metadata/en-GB/description.txt
  ios/fastlane/metadata/en-GB/keywords.txt
  ios/fastlane/metadata/en-GB/marketing_url.txt
  ios/fastlane/metadata/en-GB/promotional_text.txt
  ios/fastlane/metadata/en-GB/release_notes.txt
  ios/fastlane/metadata/fr-FR/description.txt
  ios/fastlane/metadata/fr-FR/subtitle.txt
Labels: i18n

#156 Translations update from Hosted Weblate
  ios/fastlane/metadata/fr-FR/support_url.txt
Labels: i18n

#160 Better login flow
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_fr.arb
  lib/pages/login.dart
  lib/pages/login_flow/check_server.dart
  lib/pages/login_flow/login_wallabag.dart
  lib/pages/login_flow/utils.dart
  lib/pages/login_forms/server_form.dart
  lib/providers/server_login_flow.dart
  lib/providers/server_login_flow.g.dart
  lib/wallabag/utils.dart
  tools/init_test_account.dart
Labels: enhancement

#162 Postpone the notification permission prompt as much as possible
  lib/pages/settings.dart
  lib/services/wallabag_storage.dart
Labels: enhancement

#163 Migrate current article provider to riverpod
  lib/main.dart
  lib/pages/article.dart
  lib/pages/filters.dart
  lib/pages/listing.dart
  lib/providers/article.dart
  lib/providers/article.g.dart
  lib/providers/query.dart
  lib/providers/query.g.dart
  lib/widget_keys.dart
Labels: dev

#164 Riverpod debug logs
  lib/main.dart
  lib/models/article.dart
  lib/models/article_scroll_position.dart
  lib/providers/tools/observer.dart
Labels: dev

#157 Automatic App Store metadata
  ios/fastlane/metadata/copyright.txt
  ios/upload_metadata.sh
  lib/main.dart
  lib/pages/article.dart
  lib/pages/listing.dart
  lib/pages/login_flow/login_wallabag.dart
  lib/pages/settings.dart
  lib/providers/settings.dart
  lib/widget_keys.dart
  pubspec.lock
  pubspec.yaml
  test_driver/main.dart
  test_driver/main_test.dart
  tools/capture_screenshots.dart
Labels: ops

#165 Listing screen tweaks
  lib/main.dart
  lib/pages/listing.dart
  lib/providers/query.dart
  lib/providers/query.g.dart
  lib/services/wallabag_storage.dart
Labels: enhancement

#168 Add an en-US alias for fdroid
  android/fastlane/metadata/android/en-US
Labels: ops

#169 Sign the apk provided in the release
  .github/workflows/build_and_upload.yml
  .github/workflows/pr_builder.yml
Labels: release, ops
