Repository casimir/frigoligo, pull requests merged in 2024-07, with the labels that each got.

#226 Fix wallabag refresh token update
  lib/wallabag/wallabag.dart
Labels: bug

#227 Add early support for freon
  lib/l10n/app_en.arb
  lib/pages/login.dart
  lib/pages/login_flow/check_server.dart
  lib/pages/login_flow/login_credentials.dart
  lib/pages/login_flow/login_freon.dart
  lib/pages/login_flow/login_wallabag.dart
  lib/pages/login_flow/utils.dart
  lib/pages/save.dart
  lib/pages/session_details.dart
  lib/providers/router.dart
  lib/providers/server_login_flow.dart
  lib/server/freon.dart
  lib/server/freon.g.dart
  lib/server/providers/client.dart
  lib/server/providers/client.g.dart
  lib/server/session.dart
  lib/server/session.g.dart
  lib/services/wallabag_storage.dart
  lib/wallabag/client.dart
  lib/wallabag/credentials.dart
  lib/wallabag/models/info.dart
  lib/wallabag/models/info.g.dart
  lib/wallabag/wallabag.dart
  lib/widgets/remote_sync_progress_indicator.dart
Labels: dev

#222 Translations update from Hosted Weblate
  fastlane/metadata/android/pt/changelogs/30.txt
  fastlane/metadata/android/pt/changelogs/34.txt
  fastlane/metadata/android/pt/changelogs/default.txt
  fastlane/metadata/android/pt/full_description.txt
  fastlane/metadata/android/pt/short_description.txt
  fastlane/metadata/android/pt/title.txt
  fastlane/metadata/android/zh-TW/full_description.txt
  fastlane/metadata/android/zh-TW/short_description.txt
  fastlane/metadata/android/zh-TW/title.txt
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_zh_Hant.arb
Labels: i18n

#228 New locales (zh-Hant & ru)
  fastlane/metadata/android/en-US/changelogs/35.txt
  fastlane/metadata/android/fr-FR/changelogs/35.txt
  ios/Podfile.lock
  lib/pages/listing.dart
  lib/providers/settings.dart
  lib/widget_keys.dart
  test_driver/localization_loader.dart
  test_driver/main.dart
  test_driver/main_test.dart
  tools/capture_screenshots.dart
Labels: dev, i18n

#230 Allow connection to the server with a self-signed certificate
  fastlane/metadata/android/en-US/changelogs/35.txt
  fastlane/metadata/android/fr-FR/changelogs/35.txt
  lib/l10n/app_en.arb
  lib/main.dart
  lib/pages/login_flow/check_server.dart
  lib/pages/login_flow/login_credentials.dart
  lib/pages/login_flow/login_freon.dart
  lib/pages/login_flow/login_wallabag.dart
  lib/providers/server_login_flow.dart
  lib/providers/server_login_flow.g.dart
  lib/server/check.dart
  lib/server/freon.dart
  lib/server/providers/client.dart
  lib/server/providers/client.g.dart
  lib/server/session.dart
  lib/wallabag/client.dart
  lib/wallabag/wallabag.dart
Labels: enhancement

#229 Translations update from Hosted Weblate
  fastlane/metadata/android/de-DE/changelogs/33.txt
  fastlane/metadata/android/de-DE/changelogs/34.txt
  fastlane/metadata/android/de-DE/changelogs/35.txt
  fastlane/metadata/android/de-DE/changelogs/default.txt
  fastlane/metadata/android/de-DE/short_description.txt
  fastlane/metadata/android/fr-FR/changelogs/34.txt
  fastlane/metadata/android/fr-FR/changelogs/35.txt
  fastlane/metadata/android/fr-FR/changelogs/default.txt
  fastlane/metadata/android/fr-FR/short_description.txt
  fastlane/metadata/android/gl-ES/changelogs/35.txt
  fastlane/metadata/android/gl-ES/changelogs/default.txt
  fastlane/metadata/android/gl-ES/short_description.txt
  fastlane/metadata/android/pt/changelogs/33.txt
  fastlane/metadata/android/pt/changelogs/35.txt
  fastlane/metadata/android/pt/changelogs/default.txt
  fastlane/metadata/android/pt/short_description.txt
  lib/l10n/app_de.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_gl.arb
Labels: i18n

#234 Fix typo in language label (DE)
  lib/providers/settings.dart
Labels: bug
