Repository casimir/frigoligo, pull requests merged in 2024-03, with the labels that each got.

#132 Bump everything (flutter, deps, pods, app version)
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  pubspec.lock
  pubspec.yaml
Labels: ops

#136 Better scroll position management
  lib/models/article_scroll_position.dart
  lib/models/article_scroll_position.g.dart
  lib/pages/article.dart
  lib/providers/article.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#140 Upgrade flutter dependencies
  pubspec.lock
  pubspec.yaml
Labels: dependencies

#142 Persist pending remote sync actions until there are sent to the server
  lib/models/db.dart
  lib/models/remote_action.dart
  lib/models/remote_action.g.dart
  lib/services/remote_sync.dart
  lib/services/remote_sync_actions/articles.dart
  lib/services/remote_sync_actions/base.dart
Labels: enhancement

#137 Translations update from Hosted Weblate
  lib/l10n/app_fr.arb
Labels: i18n

#143 Translations update from Hosted Weblate
  lib/l10n/app_fr.arb
Labels: i18n

#145 Add a deeplink action to open the log console
  README.md
  lib/main.dart
  lib/providers/deeplinks.dart
Labels: enhancement

#147 Clear pending actions when clearing local data
  lib/services/wallabag_storage.dart
Labels: enhancement

#146 Move settings backend usages from provider to riverpod
  lib/main.dart
  lib/pages/listing.dart
  lib/pages/login.dart
  lib/pages/save.dart
  lib/pages/session_details.dart
  lib/pages/settings.dart
  lib/providers/ios/settings_syncer.dart
  lib/providers/settings.dart
  lib/providers/settings.g.dart
  lib/services/remote_sync.dart
  lib/services/wallabag_storage.dart
  test/smoke_test.dart
Labels: dev

#149 Localization settings enhancements
  lib/l10n/app_en.arb
  lib/pages/settings.dart
  lib/providers/settings.dart
Labels: enhancement

#150 Rework the settings screen
  lib/app_info.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/pages/settings.dart
Labels: enhancement

#152 Keep settings sections readable on Android
  lib/pages/settings.dart
Labels: enhancement

#153 Translations update from Hosted Weblate
  lib/l10n/app_de.arb
  lib/l10n/app_fr.arb
Labels: i18n
