Repository casimir/frigoligo, pull requests merged in 2024-08, with the labels that each got.

#235 Translations update from Hosted Weblate
  lib/l10n/app_eo.arb
Labels: i18n

#238 New language: Esperanto
  fastlane/metadata/android/en-US/changelogs/36.txt
  fastlane/metadata/android/fr-FR/changelogs/36.txt
  fastlane/metadata/ios/de-DE/release_notes.txt
  fastlane/metadata/ios/en-US/release_notes.txt
  fastlane/metadata/ios/fr-FR/release_notes.txt
  fastlane/metadata/ios/pt-PT/release_notes.txt
  lib/main.dart
  lib/providers/settings.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#239 Make the session details screen more readable on large screen
  lib/pages/session_details.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#245 Fix several bugs in the login form
  lib/pages/login_flow/login_credentials.dart
Labels: bug

#249 Fix a few post-migration bugs and regressions
  lib/db/converters/containers.dart
  lib/db/daos/articles.dart
  lib/db/daos/articles.g.dart
  lib/db/database.dart
  lib/db/database.g.dart
  lib/db/models/article.dart
  lib/main.dart
  lib/providers/article.dart
  lib/providers/article.g.dart
  lib/services/remote_sync.dart
  lib/services/remote_sync.g.dart
  lib/services/wallabag_storage.dart
  lib/services/wallabag_storage.g.dart
  lib/wallabag/client.dart
Labels: dev

#237 Translations update from Hosted Weblate
  lib/l10n/app_pt.arb
  lib/l10n/app_pt_PT.arb
  lib/l10n/app_zh.arb
Labels: i18n
