Repository casimir/frigoligo, pull requests merged in 2024-01, with the labels that each got.

#114 Invalid session refresh
  lib/l10n/app_en.arb
  lib/pages/listing.dart
  lib/pages/login.dart
  lib/pages/session_details.dart
  lib/services/wallabag_storage.dart
  lib/wallabag/wallabag.dart
  lib/widgets/remote_sync_progress_indicator.dart
Labels: enhancement

#115 Refresh tag list when clearing filter
  lib/pages/tags_selector/dialog.dart
Labels: bug

#90 Build the macOS version on XcodeCloud
  macos/Podfile
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner/Assets.xcassets/AppIcon.appiconset/1024-mac.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/128-mac.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/16-mac.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/256-mac.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/32-mac.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/512-mac.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/64-mac.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_16.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_256.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_64.png
  macos/Runner/Info.plist
  macos/ci_scripts/ci_post_clone.sh
Labels: ops

#117 Background server syncing
  .editorconfig
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/constants.dart
  lib/main.dart
  lib/pages/login.dart
  lib/pages/settings.dart
  lib/services/remote_sync.dart
  lib/services/remote_sync_actions/articles.dart
  lib/services/wallabag_storage.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#118 Disable login button until checks are passed
  lib/pages/login.dart
Labels: enhancement

#119 Allow to choose application language
  lib/l10n/app_en.arb
  lib/main.dart
  lib/pages/settings.dart
  lib/providers/settings.dart
Labels: enhancement

#113 Translations update from Hosted Weblate
  lib/l10n/app_de.arb
  lib/l10n/app_fr.arb
Labels: i18n

#121 In dynamic layout mode, open the drawer on start
  lib/main.dart
  lib/pages/article.dart
Labels: enhancement

#122 Translate more strings
  lib/l10n/app_en.arb
  lib/pages/filters.dart
  lib/pages/listing.dart
  lib/pages/tags_selector/dialog.dart
  lib/string_extension.dart
Labels: i18n

#123 Translations update from Hosted Weblate
  lib/l10n/app_fr.arb
Labels: help wanted, i18n

#126 Translations update from Hosted Weblate
  lib/l10n/app_de.arb
Labels: i18n

#128 Fix minimum iOS version
  ios/Flutter/AppFrameworkInfo.plist
  ios/Runner.xcodeproj/project.pbxproj
Labels: ops
