Repository casimir/frigoligo, pull requests merged in 2024-11, with the labels that each got.

#264 Refactor screenshot automation
  README.md
  assets/screenshots/dekstop.png
  assets/screenshots/desktop.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/android_phone_1-listing.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/android_phone_2-filters.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/android_phone_2-reading-settings.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/android_phone_3-reading-settings.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/android_phone_3-settings.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/android_phone_4-reading-settings-dark.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/android_phone_4-settings.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/android_phone_5-reading-settings-dark.png
  lib/main.dart
  lib/pages/articles/listing.dart
  lib/pages/reading/article.dart
  lib/widget_keys.dart
  macos/Podfile.lock
  test_driver/main_test.dart
Labels: dev

#265 Translations update from Hosted Weblate
  fastlane/metadata/android/de-DE/changelogs/36.txt
  lib/l10n/app_de.arb
  lib/l10n/app_et.arb
Labels: i18n

#268 fix(wallabag): allow null values in non-null published_by field
  lib/wallabag/models/entry.dart
  lib/wallabag/models/entry.g.dart
Labels: bug

#267 Automate changelog generation with git-cliff
  .github/workflows/update_changelog.yml
  CHANGELOG.md
  cliff.toml
Labels: ops

#277 refactor(settings): change how enum values are handled
  lib/providers/settings.dart
  lib/providers/settings.g.dart
Labels: dev

#272 Translations update from Hosted Weblate
  fastlane/metadata/android/es-ES/changelogs/30.txt
  fastlane/metadata/android/es-ES/changelogs/33.txt
  fastlane/metadata/android/es-ES/changelogs/34.txt
  fastlane/metadata/android/es-ES/changelogs/35.txt
  fastlane/metadata/android/es-ES/changelogs/36.txt
  fastlane/metadata/android/es-ES/changelogs/default.txt
  fastlane/metadata/android/es-ES/full_description.txt
  fastlane/metadata/android/es-ES/short_description.txt
  fastlane/metadata/android/es-ES/title.txt
  lib/l10n/app_es.arb
  lib/l10n/app_pt_PT.arb
Labels: i18n

#274 feat: build the app for linux arm64
  .github/workflows/build_and_upload.yml
Labels: enhancement
