Repository casimir/frigoligo, pull requests merged in 2024-06, with the labels that each got.

#208 Avoid blocking the syncer with a 404 error on article deletion
  lib/wallabag/wallabag.dart
Labels: bug

#207 Refactor routing logic for the article view
  README.md
  ios/Podfile.lock
  lib/applinks/handler.dart
  lib/main.dart
  lib/pages/article.dart
  lib/pages/home.dart
  lib/pages/listing.dart
  lib/pages/save.dart
  lib/providers/open_article.dart
  lib/providers/router.dart
  lib/providers/router.g.dart
  lib/services/remote_sync.dart
  macos/Podfile.lock
Labels: enhancement

#209 Fix actions not syncing in some cases
  lib/services/remote_sync.dart
Labels: bug

#192 Consolidate fastlane metadata
  .gitignore
  fastlane/Appfile
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/README.md
  fastlane/metadata/ios/copyright.txt
  fastlane/metadata/ios/en-US/description.txt
  fastlane/metadata/ios/en-US/keywords.txt
  fastlane/metadata/ios/en-US/name.txt
  fastlane/metadata/ios/en-US/privacy_url.txt
  fastlane/metadata/ios/en-US/subtitle.txt
  fastlane/metadata/ios/en-US/support_url.txt
  fastlane/metadata/ios/fr-FR/description.txt
  fastlane/metadata/ios/fr-FR/keywords.txt
  fastlane/metadata/ios/fr-FR/name.txt
  fastlane/metadata/ios/fr-FR/subtitle.txt
  fastlane/metadata/ios/primary_category.txt
  fastlane/metadata/ios/primary_first_sub_category.txt
  fastlane/metadata/ios/primary_second_sub_category.txt
  fastlane/metadata/ios/secondary_category.txt
  fastlane/metadata/ios/secondary_first_sub_category.txt
  fastlane/metadata/ios/secondary_second_sub_category.txt
  ios/.gitignore
  ios/fastlane/Fastfile
  ios/fastlane/metadata/en-GB/description.txt
  ios/fastlane/metadata/en-GB/name.txt
  ios/fastlane/metadata/en-GB/subtitle.txt
  ios/fastlane/metadata/fr-FR/description.txt
  ios/fastlane/metadata/fr-FR/subtitle.txt
  ios/fastlane/metadata/fr-FR/support_url.txt
  ios/upload_metadata.sh
  tools/setup_metadata_links.dart
Labels: ops, i18n

#186 Translations update from Hosted Weblate
  fastlane/metadata/android/de-DE/changelogs/30.txt
  fastlane/metadata/android/de-DE/full_description.txt
  fastlane/metadata/android/de-DE/short_description.txt
  fastlane/metadata/android/de-DE/title.txt
  fastlane/metadata/android/fr-FR/title.txt
  fastlane/metadata/android/gl-ES/changelogs/30.txt
  fastlane/metadata/android/gl-ES/full_description.txt
  fastlane/metadata/android/gl-ES/short_description.txt
  fastlane/metadata/android/gl-ES/title.txt
  ios/fastlane/metadata/gl-ES/description.txt
  ios/fastlane/metadata/gl-ES/keywords.txt
  ios/fastlane/metadata/gl-ES/name.txt
  ios/fastlane/metadata/gl-ES/privacy_url.txt
  ios/fastlane/metadata/gl-ES/subtitle.txt
  ios/fastlane/metadata/gl-ES/support_url.txt
  ios/fastlane/metadata/pt-BR/description.txt
  ios/fastlane/metadata/pt-BR/keywords.txt
  ios/fastlane/metadata/pt-BR/name.txt
  ios/fastlane/metadata/pt-BR/privacy_url.txt
  ios/fastlane/metadata/pt-BR/subtitle.txt
  ios/fastlane/metadata/pt-BR/support_url.txt
  ios/fastlane/metadata/zh-CN/description.txt
  ios/fastlane/metadata/zh-CN/keywords.txt
  ios/fastlane/metadata/zh-CN/name.txt
  ios/fastlane/metadata/zh-CN/privacy_url.txt
  ios/fastlane/metadata/zh-CN/subtitle.txt
  ios/fastlane/metadata/zh-CN/support_url.txt
  lib/l10n/app_gl.arb
  lib/l10n/app_pt_BR.arb
  lib/l10n/app_zh_Hans.arb
Labels: i18n

#210 Add 3 languages in settings: gl, pt_BR, zh
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_Hans.arb
  lib/providers/settings.dart
Labels: enhancement, i18n

#211 Translations update from Hosted Weblate
  fastlane/metadata/android/pt-BR/full_description.txt
  fastlane/metadata/android/pt-BR/short_description.txt
  fastlane/metadata/android/pt-BR/title.txt
  fastlane/metadata/android/zh-CN/full_description.txt
  fastlane/metadata/android/zh-CN/short_description.txt
  fastlane/metadata/android/zh-CN/title.txt
Labels: i18n

#212 Prepare metadata for the incoming release (1.1.0+33)
  fastlane/metadata/android/en-US/changelogs/33.txt
  fastlane/metadata/android/fr-FR/changelogs/33.txt
  fastlane/metadata/ios/de-DE/description.txt
  fastlane/metadata/ios/de-DE/name.txt
  fastlane/metadata/ios/de-DE/subtitle.txt
  fastlane/metadata/ios/gl-ES/description.txt
  fastlane/metadata/ios/gl-ES/name.txt
  fastlane/metadata/ios/gl-ES/subtitle.txt
  fastlane/metadata/ios/pt-BR/description.txt
  fastlane/metadata/ios/pt-BR/name.txt
  fastlane/metadata/ios/pt-BR/subtitle.txt
  fastlane/metadata/ios/zh-CN/description.txt
  fastlane/metadata/ios/zh-CN/name.txt
  fastlane/metadata/ios/zh-CN/subtitle.txt
  tools/setup_metadata_links.dart
Labels: release

#214 Prepare release 1.1.0+33
  README.md
  fastlane/Fastfile
  fastlane/metadata/android/en-US/changelogs/33.txt
  fastlane/metadata/android/en-US/images/phoneScreenshots/android_phone_1-listing.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/android_phone_2-filters.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/android_phone_3-reading-settings.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/android_phone_4-settings.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/android_phone_5-reading-settings-dark.png
  fastlane/metadata/android/fr-FR/changelogs/33.txt
  fastlane/metadata/android/pt-BR/short_description.txt
  fastlane/metadata/ios/en-US/release_notes.txt
  fastlane/metadata/ios/fr-FR/release_notes.txt
  fastlane/metadata/ios/gl-ES/description.txt
  fastlane/metadata/ios/gl-ES/name.txt
  fastlane/metadata/ios/gl-ES/subtitle.txt
  fastlane/metadata/ios/zh-Hans/description.txt
  fastlane/metadata/ios/zh-Hans/name.txt
  fastlane/metadata/ios/zh-Hans/subtitle.txt
  ios/Runner.xcodeproj/project.pbxproj
  ios/fastlane/metadata/gl-ES/description.txt
  ios/fastlane/metadata/gl-ES/keywords.txt
  ios/fastlane/metadata/gl-ES/name.txt
  ios/fastlane/metadata/gl-ES/privacy_url.txt
  ios/fastlane/metadata/gl-ES/subtitle.txt
  ios/fastlane/metadata/gl-ES/support_url.txt
  ios/fastlane/metadata/pt-BR/description.txt
  ios/fastlane/metadata/pt-BR/keywords.txt
  ios/fastlane/metadata/pt-BR/name.txt
  ios/fastlane/metadata/pt-BR/privacy_url.txt
  ios/fastlane/metadata/pt-BR/subtitle.txt
  ios/fastlane/metadata/pt-BR/support_url.txt
  ios/fastlane/metadata/zh-CN/description.txt
  ios/fastlane/metadata/zh-CN/keywords.txt
  ios/fastlane/metadata/zh-CN/name.txt
  ios/fastlane/metadata/zh-CN/privacy_url.txt
  ios/fastlane/metadata/zh-CN/subtitle.txt
  ios/fastlane/metadata/zh-CN/support_url.txt
  test_driver/main.dart
  test_driver/main_test.dart
  tools/capture_screenshots.dart
  tools/setup_metadata.dart
  tools/setup_metadata_links.dart
Labels: release

#215 Use universal_platform to simply the web experimentation
  lib/constants.dart
  lib/main.dart
  lib/pages/reading_settings_configurator.dart
  lib/pages/settings.dart
  lib/providers/settings.dart
  lib/wallabag/credentials.dart
  pubspec.lock
  pubspec.yaml
Labels: dev

#218 Can't open links inside article on Android
  android/app/src/main/AndroidManifest.xml
Labels: bug

#220 Change for a more explicit short description
  appimage/Frigoligo.desktop
  fastlane/metadata/android/de-DE/short_description.txt
  fastlane/metadata/android/en-US/short_description.txt
  fastlane/metadata/android/fr-FR/short_description.txt
  fastlane/metadata/android/gl-ES/short_description.txt
  fastlane/metadata/android/pt-BR/short_description.txt
  fastlane/metadata/android/zh-CN/short_description.txt
  fastlane/metadata/ios/fr-FR/subtitle.txt
  pubspec.yaml
  tools/setup_metadata.dart
Labels: documentation, i18n

#221 Avoid manual modification of iOS build files
  ios/Runner.xcodeproj/project.pbxproj
Labels: release, dev

#213 Translations update from Hosted Weblate
  fastlane/metadata/android/gl-ES/changelogs/33.txt
  fastlane/metadata/android/gl-ES/changelogs/34.txt
  fastlane/metadata/android/gl-ES/changelogs/default.txt
Labels: i18n

#224 Change wallabag client architecture
  lib/app_info.dart
  lib/pages/login_flow/check_server.dart
  lib/pages/login_flow/login_wallabag.dart
  lib/pages/save.dart
  lib/providers/server_login_flow.dart
  lib/providers/server_login_flow.g.dart
  lib/server/check.dart
  lib/services/wallabag_storage.dart
  lib/wallabag/client.dart
  lib/wallabag/client.g.dart
  lib/wallabag/utils.dart
  lib/wallabag/wallabag.dart
  lib/wallabag/wallabag.g.dart
  lib/widgets/remote_sync_progress_indicator.dart
  tools/init_test_account.dart
Labels: dev
